#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum MainnetFamily {
    Monero,
    Bitcoin,
    Litecoin,
    Dogecoin,
    BitcoinCash,
    BitcoinSv,
    Dash,
    Zcash,
    Ravencoin,
    Bitcoinz,
    Monacoin,
    BitcoinLike,
    Solana,
    Algorand,
    Near,
    Cardano,
    Polkadot,
    Kusama,
    Acala,
    Astar,
    Shiden,
    Ripple,
    Tron,
    Stellar,
    Sui,
    Aptos,
    Multiversx,
    Eos,
    Hedera,
    Icon,
    Mina,
    Neo3,
    Nimiq,
    Ontology,
    Pocket,
    Dock,
    Defichain,
    Flow,
    Stacks,
    Starknet,
    Tezos,
    Theta,
    Ton,
    Terra,
    Vechain,
    Waves,
    Zilliqa,
    Everscale,
    Factom,
    Flux,
    CosmosHub,
    Osmosis,
    Juno,
    Akash,
    Injective,
    Regen,
    Stargaze,
    Secret,
    Band,
    Ion,
    GravityBridge,
    Cronos,
    Kava,
    Agoric,
    Axelar,
    Cheqd,
    Coreum,
    Shentu,
    Dydx,
    Dymension,
    Fetch,
    Initia,
    Kyve,
    Neutron,
    Oraichain,
    Persistence,
    Sei,
    Celestia,
    Thorchain,
    AlephZero,
    Avail,
    Bittensor,
    Centrifuge,
    Karura,
    Picasso,
    Polkadex,
    Polymesh,
    Ternoa,
    Vara,
    Evm,
}

/// Resolve Trocador's generic `Mainnet` label into an internal derivation family.
///
/// The catalog is intentionally explicit for known native chains. Any remaining
/// `Mainnet` ticker falls back to the repo's generic EVM derivation so the full
/// bundled snapshot remains routable for address generation.
pub fn mainnet_family(ticker_lower: &str) -> MainnetFamily {
    match ticker_lower {
        // Native UTXO-style chains
        "xmr" => MainnetFamily::Monero,
        "btc" => MainnetFamily::Bitcoin,
        "ltc" => MainnetFamily::Litecoin,
        "doge" => MainnetFamily::Dogecoin,
        "bch" => MainnetFamily::BitcoinCash,
        "bsv" | "bchsv" => MainnetFamily::BitcoinSv,
        "dash" => MainnetFamily::Dash,
        "zec" => MainnetFamily::Zcash,
        "rvn" => MainnetFamily::Ravencoin,
        "btcz" => MainnetFamily::Bitcoinz,
        "mona" => MainnetFamily::Monacoin,
        "vtc" | "dgb" | "grs" | "nmc" | "via" | "pivx" | "sys" | "btg" | "kmd" | "arrr"
        | "firo" => MainnetFamily::BitcoinLike,

        // Existing dedicated implementations
        "sol" => MainnetFamily::Solana,
        "algo" => MainnetFamily::Algorand,
        "near" => MainnetFamily::Near,
        "ada" => MainnetFamily::Cardano,
        "dot" => MainnetFamily::Polkadot,
        "ksm" => MainnetFamily::Kusama,
        "aca" => MainnetFamily::Acala,
        "astr" => MainnetFamily::Astar,
        "sdn" => MainnetFamily::Shiden,
        "xrp" => MainnetFamily::Ripple,
        "trx" => MainnetFamily::Tron,
        "xlm" => MainnetFamily::Stellar,
        "sui" => MainnetFamily::Sui,
        "apt" => MainnetFamily::Aptos,
        "egld" => MainnetFamily::Multiversx,
        "eos" | "a" | "waxp" | "xpr" => MainnetFamily::Eos,
        "hbar" => MainnetFamily::Hedera,
        "icx" => MainnetFamily::Icon,
        "mina" => MainnetFamily::Mina,
        "neo3" => MainnetFamily::Neo3,
        "nim" => MainnetFamily::Nimiq,
        "ont" | "ong" => MainnetFamily::Ontology,
        "pokt" => MainnetFamily::Pocket,
        "dock" => MainnetFamily::Dock,
        "dfi" => MainnetFamily::Defichain,
        "flow" => MainnetFamily::Flow,
        "stx" => MainnetFamily::Stacks,
        "strk" => MainnetFamily::Starknet,
        "xtz" => MainnetFamily::Tezos,
        "theta" | "tfuel" | "tdrop" => MainnetFamily::Theta,
        "ton" => MainnetFamily::Ton,
        "luna" | "lunc" => MainnetFamily::Terra,
        "vet" => MainnetFamily::Vechain,
        "waves" => MainnetFamily::Waves,
        "zil" => MainnetFamily::Zilliqa,
        "ever" => MainnetFamily::Everscale,
        "fact" | "fct" => MainnetFamily::Factom,
        "flux" => MainnetFamily::Flux,

        // Cosmos-like families already represented in the repo
        "atom" => MainnetFamily::CosmosHub,
        "osmo" => MainnetFamily::Osmosis,
        "juno" => MainnetFamily::Juno,
        "akt" => MainnetFamily::Akash,
        "inj" => MainnetFamily::Injective,
        "regen" => MainnetFamily::Regen,
        "stars" => MainnetFamily::Stargaze,
        "scrt" => MainnetFamily::Secret,
        "band" => MainnetFamily::Band,
        "ion" => MainnetFamily::Ion,
        "gravitybg" => MainnetFamily::GravityBridge,
        "cro" => MainnetFamily::Cronos,
        "kava" => MainnetFamily::Kava,
        "bld" => MainnetFamily::Agoric,
        "axel" => MainnetFamily::Axelar,
        "cheq" => MainnetFamily::Cheqd,
        "coreum" => MainnetFamily::Coreum,
        "ctk" => MainnetFamily::Shentu,
        "dydx" => MainnetFamily::Dydx,
        "dym" => MainnetFamily::Dymension,
        "fet" => MainnetFamily::Fetch,
        "init" => MainnetFamily::Initia,
        "kyve" => MainnetFamily::Kyve,
        "ntrn" => MainnetFamily::Neutron,
        "orai" => MainnetFamily::Oraichain,
        "xprt" => MainnetFamily::Persistence,
        "sei" => MainnetFamily::Sei,
        "tia" => MainnetFamily::Celestia,
        "rune" => MainnetFamily::Thorchain,

        // Substrate-like families
        "azero" => MainnetFamily::AlephZero,
        "avail" => MainnetFamily::Avail,
        "tao" => MainnetFamily::Bittensor,
        "cfg" => MainnetFamily::Centrifuge,
        "kar" => MainnetFamily::Karura,
        "pica" => MainnetFamily::Picasso,
        "pdex" => MainnetFamily::Polkadex,
        "polyx" => MainnetFamily::Polymesh,
        "caps" => MainnetFamily::Ternoa,
        "vara" => MainnetFamily::Vara,

        // Remaining ambiguous Mainnet tickers use the repo's generic EVM family.
        _ => MainnetFamily::Evm,
    }
}
