CREATE TABLE IF NOT EXISTS giftcard_orders (
    id VARCHAR(36) COLLATE utf8mb4_unicode_ci PRIMARY KEY,
    user_id VARCHAR(36) COLLATE utf8mb4_unicode_ci NULL,
    client_id VARCHAR(64) NULL,
    owner_key VARCHAR(128) NOT NULL,
    request_hash CHAR(64) NOT NULL,
    order_kind VARCHAR(16) NOT NULL,
    product_id VARCHAR(120) NULL,
    prepaid_provider VARCHAR(120) NULL,
    currency_code VARCHAR(12) NULL,
    source_ticker VARCHAR(20) NOT NULL,
    source_network VARCHAR(50) NOT NULL,
    amount DECIMAL(36, 18) NOT NULL,
    recipient_email VARCHAR(320) NOT NULL,
    card_markup VARCHAR(10) NULL,
    webhook_mode VARCHAR(16) NOT NULL DEFAULT 'none',
    webhook_url VARCHAR(2048) NULL,
    upstream_trade_id VARCHAR(100) NULL,
    provider VARCHAR(255) NULL,
    provider_trade_id VARCHAR(255) NULL,
    provider_password VARCHAR(255) NULL,
    target_ticker VARCHAR(20) NULL,
    target_network VARCHAR(50) NULL,
    source_coin_name VARCHAR(120) NULL,
    target_coin_name VARCHAR(120) NULL,
    amount_to DECIMAL(36, 18) NULL,
    fixed BOOLEAN NULL,
    payment BOOLEAN NULL,
    deposit_address TEXT NULL,
    deposit_extra_id VARCHAR(255) NULL,
    settlement_address TEXT NULL,
    settlement_extra_id VARCHAR(255) NULL,
    refund_address TEXT NULL,
    refund_extra_id VARCHAR(255) NULL,
    provider_status VARCHAR(64) NULL,
    details_json LONGTEXT NULL,
    status VARCHAR(32) NOT NULL DEFAULT 'queued',
    last_error TEXT NULL,
    attempt_count INT NOT NULL DEFAULT 0,
    next_retry_at DATETIME NULL,
    last_synced_at DATETIME NULL,
    completed_at DATETIME NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT fk_giftcard_orders_user
        FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL,
    UNIQUE KEY uq_giftcard_orders_upstream_trade_id (upstream_trade_id),
    INDEX idx_giftcard_orders_owner_created (owner_key, created_at),
    INDEX idx_giftcard_orders_client_created (client_id, created_at),
    INDEX idx_giftcard_orders_request_hash (owner_key, request_hash, created_at),
    INDEX idx_giftcard_orders_queue (status, next_retry_at, created_at),
    INDEX idx_giftcard_orders_upstream_status (provider_status, updated_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
