#!/bin/bash
./scripts/rpc/check_algorand.sh
./scripts/rpc/check_apechain.sh
./scripts/rpc/check_aptos.sh
./scripts/rpc/check_arbitrum.sh
./scripts/rpc/check_astar.sh
./scripts/rpc/check_aurora.sh
./scripts/rpc/check_avalanche.sh
./scripts/rpc/check_b2.sh
./scripts/rpc/check_base.sh
./scripts/rpc/check_bitcoin.sh
./scripts/rpc/check_bitcoin_cash.sh
./scripts/rpc/check_bitgert.sh
./scripts/rpc/check_blast.sh
./scripts/rpc/check_boba.sh
./scripts/rpc/check_botanix.sh
./scripts/rpc/check_bsc.sh
./scripts/rpc/check_bttc.sh
./scripts/rpc/check_cardano.sh
./scripts/rpc/check_celo.sh
./scripts/rpc/check_cfx.sh
./scripts/rpc/check_chiliz.sh
./scripts/rpc/check_conflux_espace.sh
./scripts/rpc/check_core.sh
./scripts/rpc/check_cosmos.sh
./scripts/rpc/check_cronos.sh
./scripts/rpc/check_cyber.sh
./scripts/rpc/check_dash.sh
./scripts/rpc/check_digibyte.sh
./scripts/rpc/check_dock.sh
./scripts/rpc/check_dogecoin.sh
./scripts/rpc/check_elrond.sh
./scripts/rpc/check_eth.sh
./scripts/rpc/check_evmos.sh
./scripts/rpc/check_fantom.sh
./scripts/rpc/check_filecoin.sh
./scripts/rpc/check_flare.sh
./scripts/rpc/check_flow.sh
./scripts/rpc/check_fraxtal.sh
./scripts/rpc/check_fuse.sh
./scripts/rpc/check_gnosis.sh
./scripts/rpc/check_gravity.sh
./scripts/rpc/check_harmony.sh
./scripts/rpc/check_hyper_evm.sh
./scripts/rpc/check_icon.sh
./scripts/rpc/check_iota_evm.sh
./scripts/rpc/check_iotex.sh
./scripts/rpc/check_islm_evm.sh
./scripts/rpc/check_kaia.sh
./scripts/rpc/check_kava.sh
./scripts/rpc/check_kcc.sh
./scripts/rpc/check_klaytn.sh
./scripts/rpc/check_kusama.sh
./scripts/rpc/check_linea.sh
./scripts/rpc/check_litecoin.sh
./scripts/rpc/check_manta.sh
./scripts/rpc/check_mantle.sh
./scripts/rpc/check_merlin.sh
./scripts/rpc/check_metis.sh
./scripts/rpc/check_midnight.sh
./scripts/rpc/check_mina.sh
./scripts/rpc/check_mode.sh
./scripts/rpc/check_monad.sh
./scripts/rpc/check_monero.sh
./scripts/rpc/check_moonbeam.sh
./scripts/rpc/check_moonriver.sh
./scripts/rpc/check_morph.sh
./scripts/rpc/check_near.sh
./scripts/rpc/check_neo.sh
./scripts/rpc/check_oasis.sh
./scripts/rpc/check_okx_chain.sh
./scripts/rpc/check_opbnb.sh
./scripts/rpc/check_optimism.sh
./scripts/rpc/check_osmosis.sh
./scripts/rpc/check_polkadot.sh
./scripts/rpc/check_polygon.sh
./scripts/rpc/check_pulsechain.sh
./scripts/rpc/check_ravencoin.sh
./scripts/rpc/check_redbelly.sh
./scripts/rpc/check_rei.sh
./scripts/rpc/check_ronin.sh
./scripts/rpc/check_rsk.sh
./scripts/rpc/check_scroll.sh
./scripts/rpc/check_sei.sh
./scripts/rpc/check_shibarium.sh
./scripts/rpc/check_solana.sh
./scripts/rpc/check_sonic.sh
./scripts/rpc/check_stacks.sh
./scripts/rpc/check_starknet.sh
./scripts/rpc/check_stellar.sh
./scripts/rpc/check_step_network.sh
./scripts/rpc/check_sui.sh
./scripts/rpc/check_sysnevm.sh
./scripts/rpc/check_taiko.sh
./scripts/rpc/check_telos.sh
./scripts/rpc/check_tezos.sh
./scripts/rpc/check_thundercore.sh
./scripts/rpc/check_tomochain.sh
./scripts/rpc/check_ton.sh
./scripts/rpc/check_tron.sh
./scripts/rpc/check_vechain.sh
./scripts/rpc/check_velas.sh
./scripts/rpc/check_wanchain.sh
./scripts/rpc/check_waves.sh
./scripts/rpc/check_x_layer.sh
./scripts/rpc/check_xdai.sh
./scripts/rpc/check_xrp.sh
./scripts/rpc/check_zcash.sh
./scripts/rpc/check_zeta.sh
./scripts/rpc/check_zilliqa.sh
./scripts/rpc/check_zkfair.sh
./scripts/rpc/check_zksync_era.sh
./scripts/rpc/check_zora.sh
